import 'rxjs/add/observable/fromPromise'
import 'rxjs/add/operator/mergeMap'
import 'rxjs/add/observable/throw'
import 'rxjs/add/operator/concatMap'
import 'rxjs/add/operator/catch'
import 'rxjs/add/observable/of'
